### ISSUE TITLE
popuko mis-detects "unmergeable" pull request if the upstream has been changed

### ISSUE THREAD

**Issue by vg-1000ch** [karen-irc/popuko#187]
### Problem

masterへのmergeに伴う，他のブランチのmergable判定時，conflictを誤検出している

### How Reproducible

masterへの merge時．頻繁に発生が確認されている.

ただし，誤検出が起こる場合と起こらない場合があり，その詳細な条件は未知．

### Expected Result

conflictしないbranchにおいては，ラベル付与操作をしない

### Actual Result

conflictを誤検出し，`S-need-rebase` ラベルを付与している

### How to reproduce

github上で適当なブランチを `merge master` する

### solution

現状原因不明なので，その検証から必要.

**Comment by saneyuki** [comment]
I feel this problem is caused by https://github.com/karen-irc/popuko/blob/4c8ad7a7f856abc88363443523e8ad2525063127/operation/pull_request.go#L20-L23. It's too eager for detection.

**Comment by saneyuki** [comment]
I confirm this problem is reproducible.
