### ISSUE TITLE
`r+ @popuko` のインターフェイスに対応して欲しい

### ISSUE THREAD

**Issue by azami** [karen-irc/popuko#212]
アサインは `r? @foo` の形式だが、LGTMは `@popuko r+` の形式で混乱しました。
ので `r+ @popuko` も対応して欲しいです。

**Comment by saneyuki** [comment]
Sorry. I don't think we should support it. 

This command system is based on [homu](https://github.com/barosl/homu), and I'd like to sort with it.

**Comment by nekoya** [comment]
Yes. In actual, we've considered `r+ @popuko` command.

But we decided these commands should be separated explicitly.

- You can use `r? @foo @bar` relatively casual intention
- You MUST call `@popuko r+` with explicit one (especially auto-merge mode)

Please understand it.
